plugin:
    name: 'croqo.lottie::lang.plugin.name'
    description: 'croqo.lottie::lang.plugin.description'
    author: Croqo
    icon: oc-icon-circle-thin
    homepage: ''
navigation:
    main-menu-lottie:
        label: 'croqo.lottie::lang.plugin.name'
        url: croqo/lottie/manager
        icon: icon-play
        permissions:
            - croqo.lottie.management
permissions:
    croqo.lottie.management:
        tab: 'croqo.lottie::lang.plugin.name'
        label: 'croqo.lottie::lang.file.manager'
