name: New
modelClass: Croqo\Lottie\Models\File
form: $/croqo/lottie/models/file/fields.yaml
defaultRedirect: croqo/lottie/new
create:
    redirect: 'croqo/lottie/file/:id'
    redirectClose: croqo/lottie/files
update:
    redirect: croqo/lottie/file
    redirectClose: croqo/lottie/files
preview: {  }
