name: Editor
modelClass: Croqo\Lottie\Models\File
form: $/croqo/lottie/models/file/fields.yaml
defaultRedirect: croqo/lottie/editor
create:
    title: 'croqo.lottie::lang.file.new'
    redirect: croqo/lottie/new
    redirectClose: croqo/lottie/editor
update:
    title: 'croqo.lottie::lang.file.editor'
    redirect: 'croqo/lottie/editor/update/:id'
    redirectClose: croqo/lottie/editor
